[package]
name = "gcd_calculator"
version = "0.1.0"
edition = "2021"
author = "ricky"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"